name:                ccg4c
version:             0.1.0.0
github:              "wangqingjiang-ncwu/ccg4c"
license:             BSD3
author:              "China University of Water Resources and Electric Power"
maintainer:          "wangqingjiang@ncwu.edu.cn"
copyright:           "Copyright (c) 2023 China University of Water Resources and Electric Power"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A package for Chinese-Oriented Combinatory Categorial Grammar
category:            Natural Language Understanding

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wangqingjiang-ncwu/ccg4c#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mysql-haskell
- hspec
- MissingH
- io-streams
- bytestring
- text
- directory
- time
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ccg4c-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccg4c

tests:
  ccg4c-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccg4c
